# Generated by Django 3.2.24 on 2026-07-31 15:42

from django.db import migrations
import funkwhale_api.common.models
import funkwhale_api.common.validators
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20220627_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=versatileimagefield.fields.VersatileImageField(max_length=255, upload_to=funkwhale_api.common.models.get_file_path, validators=[funkwhale_api.common.validators.ImageDimensionsValidator(min_height=50, min_width=50), funkwhale_api.common.validators.FileValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'], max_size=5242880)]),
        ),
    ]
