# Generated by Django 3.2.25 on 2026-08-05 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "object_type",
                    models.CharField(
                        choices=[("album", "Album"), ("playlist", "Playlist")],
                        max_length=16,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creation_date"],
            },
        ),
        migrations.AddIndex(
            model_name="sharelink",
            index=models.Index(
                fields=["owner", "-creation_date"],
                name="shares_shar_owner_i_96681a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sharelink",
            index=models.Index(
                fields=["object_type", "object_id"],
                name="shares_shar_object__9e52dc_idx",
            ),
        ),
    ]
