# Generated by Django 2.0.7 on 2018-07-21 13:17

import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations, models

import funkwhale_api.common.utils
import funkwhale_api.common.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                max_length=150,
                null=True,
                upload_to=funkwhale_api.common.utils.ChunkedPath(
                    "users/avatars", preserve_file_name=False
                ),
                validators=[
                    funkwhale_api.common.validators.ImageDimensionsValidator(
                        min_height=50, min_width=50
                    ),
                    funkwhale_api.common.validators.FileValidator(
                        allowed_extensions=["png", "jpg", "jpeg", "gif"],
                        max_size=2097152,
                    ),
                ],
            ),
        ),
    ]
