# Generated by Django 2.2.4 on 2019-09-20 08:57
#
# Defaults are defined locally so this historical migration stays importable
# after the support-message fields and settings were removed (see 0027).

import datetime

from django.db import migrations, models
import django.utils.timezone

# Historical default was settings.INSTANCE/FUNKWHALE_SUPPORT_MESSAGE_DELAY (=15).
_SUPPORT_MESSAGE_DELAY_DAYS = 15


def get_default_instance_support_message_display_date():
    return django.utils.timezone.now() + datetime.timedelta(
        days=_SUPPORT_MESSAGE_DELAY_DAYS
    )


def get_default_funkwhale_support_message_display_date():
    return django.utils.timezone.now() + datetime.timedelta(
        days=_SUPPORT_MESSAGE_DELAY_DAYS
    )


def set_display_date(apps, schema_editor):
    """
    Set display date for instance/funkwhale support message on existing users
    """
    User = apps.get_model("users", "User")
    now = django.utils.timezone.now()
    instance_support_message_display_date = now + datetime.timedelta(
        days=_SUPPORT_MESSAGE_DELAY_DAYS
    )
    funkwhale_support_message_display_date = now + datetime.timedelta(
        days=_SUPPORT_MESSAGE_DELAY_DAYS
    )

    User.objects.update(
        instance_support_message_display_date=instance_support_message_display_date
    )
    User.objects.update(
        funkwhale_support_message_display_date=funkwhale_support_message_display_date
    )


def rewind(*args, **kwargs):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_application_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="funkwhale_support_message_display_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                default=get_default_funkwhale_support_message_display_date,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="instance_support_message_display_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                default=get_default_instance_support_message_display_date,
            ),
        ),
        migrations.RunPython(set_display_date, rewind),
    ]
