# Generated by Django 3.2.24 on 2026-07-31 15:42

from django.db import migrations, models
import oauth2_provider.generators
import oauth2_provider.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_totp_2fa'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='totprecoverycode',
            name='users_totpr_user_id_3b8c1a_idx',
        ),
        migrations.AlterField(
            model_name='application',
            name='client_secret',
            field=oauth2_provider.models.ClientSecretField(blank=True, db_index=True, default=oauth2_provider.generators.generate_client_secret, help_text='Hashed on Save. Copy it now if this is a new secret.', max_length=255),
        ),
        migrations.AddIndex(
            model_name='totprecoverycode',
            index=models.Index(fields=['user', 'used_at'], name='users_totpr_user_id_7ba953_idx'),
        ),
    ]
