# Generated by Django 3.2.25 on 2026-08-06 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20260806_1305'),
        ('users', '0029_totp_secret_encrypted'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='oidcidentity',
            name='users_oidci_user_id_issuer_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_avatar', to='common.attachment'),
        ),
        migrations.AddField(
            model_name='user',
            name='summary_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_summary', to='common.content'),
        ),
        migrations.AddIndex(
            model_name='oidcidentity',
            index=models.Index(fields=['user', 'issuer'], name='users_oidci_user_id_db17b2_idx'),
        ),
    ]
