# Generated by Django 3.2.24 on 2026-07-31 15:42

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0008_radio_attachment_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiosession',
            name='config',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
