# Generated by Django 2.0.8 on 2018-09-14 20:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0030_auto_20180825_1411"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackfile",
            name="modification_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
