# Generated by Django 2.1.7 on 2019-04-09 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0037_auto_20190103_1757"),
    ]

    operations = []
