# Generated by Django 2.2.5 on 2019-10-21 13:18

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import funkwhale_api.music.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("music", "0039_auto_20190423_0820"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackActor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("internal", models.BooleanField(db_index=True, default=False)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_actor_items",
                        to="music.Track",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_actor_items",
                        to="music.Upload",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_actor_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("track", "user", "internal", "upload")},
            },
        ),
    ]
