# Generated by Django 3.2.25 on 2026-08-06 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0060_artistcredit_remove_album_track_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='fid',
        ),
        migrations.AddField(
            model_name='library',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libraryscan',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
