# Generated by Django 3.2.25 on 2026-08-06 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def assign_owners(apps, schema_editor):
    # Existing libraries (pre-removal databases) are attributed to the first
    # user instead of defaulting to a hardcoded pk, which would fail the FK
    # check whenever user 1 does not exist.
    Library = apps.get_model("music", "Library")
    User = apps.get_model("users", "User")
    first_user = User.objects.order_by("pk").first()
    if first_user is None:
        return
    Library.objects.filter(owner_id=None).update(owner_id=first_user.pk)


def unassign_owners(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0060_artistcredit_remove_album_track_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='fid',
        ),
        migrations.AddField(
            model_name='library',
            name='owner',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='libraries',
                to='users.user',
            ),
            preserve_default=False,
        ),
        migrations.RunPython(assign_owners, unassign_owners),
        migrations.AddField(
            model_name='libraryscan',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
