# Generated by Django 3.2.25 on 2026-08-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0061_auto_20260806_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='users.user'),
        ),
    ]
